import "./globals.css";

import type { Metadata } from "next";

import { Inter } from "next/font/google";

import Footer from "@/components/footer";

import Navbar from "@/components/navbar";

import Hero from "@/components/Hero";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={`${inter.className} max-h-screen bg-blue-500`}>
        <Navbar />
        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 text-green-600"></main>

        <Hero />
        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 text-"></main>
        {children}
        <Footer />
      </body>
    </html>
  );
}
